### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vhfsantos** [calacademy-research/ccgutils#1]
Hi,
Thank you for sharing these helpful scripts!
Would you please confirm that they are licensed under the GPL?
Thanks,
Vinícius

**Comment by jbh-cas** [comment]
They are under the MIT License.

Btw, not yet on the repo, we have versions that work with the newer BUSCO version 5 formats including bringing over Augustus found BUSCOs into the those Missing in the MetaEuk mode run. That typically increases Complete BUSCO counts a few percent. We reference this and other new scripts in a soon to be posted preprint. So we'll probably being augmenting these near term.

**Comment by vhfsantos** [comment]
Thank you very much for your reply!
